### PR TITLE
the interpreter didn't parse correctly this systax: %(sleeptime)1.2f …

### PR DESCRIPTION
**Pull request by eyalsn-stratoscale**
…seconds

### CODE REVIEW

**Comment by segev-lior** [comment]
ship it!

thanks for this

**Comment by eyalsn-stratoscale** [comment]
there are 3 more problems i'm working on it..
1. it doesn't format the float accordingly... 1.2f is shown as a full string, eg, 8.9993343232
2. if you use both args & kwargs of logging, it only parses the args
3, if you pass only a dict as a first parameter, eg: logging.warning('text %s', somedict), it will not print the dict but will try to parse it...

**Comment by guykr** [comment]
let me know if you need help

**Comment by eyalsn-stratoscale** [comment]
thanks
I'll try a bit and let you know :)

**Pull request merged**
